AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  book-a-doc

  Sample SAM Template for book-a-doc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: users/
      Handler: app.app
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        TestUser:
          Type: Api
          Properties:
            Path: /
            Method: get
        ListUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
        PutStudent:
          Type: Api
          Properties:
            Path: /users
            Method: post
        GetStudent:
          Type: Api
          Properties:
            Path: /users/{id}/
            Method: get
        PatchStudent:
          Type: Api
          Properties:
            Path: /users/{id}/
            Method: patch
        DeleteStudent:
          Type: Api
          Properties:
            Path: /users/{id}/
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserApi:
    Description: "API Gateway endpoint URL for Prod stage for User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: "Implicit IAM Role created for User function"
    Value: !GetAtt UserFunctionRole.Arn
